metadata:
  description: 'A sample data domain specification'
  distribution: 'Global'
  version: 'v0.4'

domain:
  name: domain_name
  abbreviation:
  zone: zone_name
  description: 
  location:
  owner:
    name: owner_name
    email: owner_email
  tags:
    - tag1
    - tag2
  patterns:
    - pattern1
    - pattern2
  data_products:
    - data_product1
    - data_product2
