metadata:
  description: A sample data domain specification
  distribution: Global
  version: v0.4

domain:
  abbreviation: FDD
  description: A domain for financial data
  zone: Data Processing
  location: Global
  name: Financial Data Domain
  owner:
    email: john.doe@example.com
    name: John Doe
  tags:
  - finance
  - banking
  - data
